name: web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: ben <email@example.com>

environment:
  sdk: '>=2.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  angular_forms: ^2.0.0

  js: ^0.6.1+1

  http: ^0.11.3+17

  rxdart: ^0.18.1

  api:
    path: ../../api

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.1+1
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.2+2
  test: ^1.3.0
