name: api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: ben <email@example.com>

environment:
  sdk: '>=2.0.0'

dependencies:

#  path: ^1.4.1

  http: ^0.12.0

  rxdart: ^0.18.1

  bloc: ^0.3.0

  dryice: ^2.0.22

dev_dependencies:
  test: ^1.3.0
